### ISSUE TITLE
Probably a silly question

### ISSUE THREAD

**Issue by barriteau** [redr00t/WhatsAppDesktop-NoStore#3]
Hi!

This is my output after executing `WhatsappUpdater.exe`:

```console
D:\WhatsAppDesktop-NoStore>WhatsappUpdater.exe
Downloading: 5319275A.WhatsAppDesktop_2.2342.7.0_neutral_~_cv1g1gvanyjgm.msixbundle
Download complete.
Whatsapp process stopped.
Installing the application: 5319275A.WhatsAppDesktop_2.2342.7.0_neutral_~_cv1g1gvanyjgm.msixbundle
Installation complete.
```

It seems everything went okay, but I don't know where the installed app is located, can't find any .exe, .lnk nor anything similarly named, I'm a complete ignorant about the format, location, naming or file extensions for the MS Store apps, have been on LTSC since always. Any clue?

**Comment by redr00t** [comment]
If you search for "WhatsApp" in the Windows Start menu, does the application not appear?

**Comment by barriteau** [comment]
Nope, nor in the start menu nor anywhere else; just tried again and checked for the most recent files created in the whole system, only the downloaded .msixbundle stays for a moment and after that nothing related with WhatsApp stays.

But, full disclosure, I have a kind of a hacked system, I'm pretty sure my problem relates with the fact that I'm not using the regular Windows shell (Explorer) but a replacement using the Microsoft Shell Launcher V2, so it's of no worth trying to figure out what's happening. But anyway, thanks a lot for the tool! :)
